### ISSUE TITLE
Project showing excluded

### ISSUE THREAD

**Issue by Srutiverma123** [BalajiG2000/Code_Dump#274]
Hey can you please check why it's showing project excluded!

**Comment by BalajiG2000** [comment]
Yes , it has been excluded now.

**Comment by Srutiverma123** [comment]
But what is the reason?

**Comment by BalajiG2000** [comment]
@Srutiverma123  Actually for a project to be included under hacktoberfest 2021, it should not accept Data structures and algorithms code (like merge sort.cpp) . They have a system designed to check this, and due to that reason (quality of the contribution rather than quantity) this project has been excluded. Sorry about that.
